# *************
# Configuration
# *************

# Rule identifiers to exclude from running
disabled_rules:
- trailing_whitespace
- force_cast

# Rules disabled by default we want to enable
opt_in_rules:
- empty_count
- empty_string
- vertical_whitespace

# Paths to ignore during linting.
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

# *****
# Lines
# *****

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: false
    ignores_comments: false
    ignores_urls: true

# *********
# Functions
# *********

function_body_length:
    warning: 100
    error: 200

function_parameter_count:
    warning: 6
    error: 8

# *****
# Files
# *****

type_body_length:
    warning: 500
    error: 1000

file_length:
    warning: 800
    error: 1500
    ignore_comment_only_lines: true

vertical_whitespace:
    severity: error
    max_empty_lines: 2

# ****
# Misc
# ****

cyclomatic_complexity:
    warning: 15
    error: 25

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"
