source 'https://cdn.cocoapods.org/'


platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

def common_pods
  pod 'SwiftGen'
end

target 'OrangeTrainingBox' do
    common_pods
end

post_install do |installer|
  ENV["COCOAPODS_DISABLE_STATS"] = "true"
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
                  config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
                  config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
