source 'https://github.com/CocoaPods/Specs.git'
source 'gitolite@www.forge.orange-labs.fr:orangecocoapods/public.git'

platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!


def common_pods
    pod 'SwiftGen'
    pod 'ESSAbout/Core'
end


target 'OrangeTrainingBox' do
    common_pods
end
